site_name: EE intro and examples
site_url: https://ee.liangwatcher.top/
site_author: LiangWatcher
site_description: "电子技术知识和学习经验的分享网站"
repo_name: ee-intro-and-examples
repo_name: https://github.com/liangshao07/ee-intro-and-examples
copyright: Copyright &copy; 2024-present <a href="https://github.com/liangshao07" target="_blank" rel="noopener noreferrer">LiangWatcher</a>

theme:
  name: material
  language: zh
  favicon: pic/favicon.ico
  include_search_page: false
  search_index_only: true
 
  features:
    - toc.integrate
    - highlightjs
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liangshao07/ee-intro-and-examples
  analytics:
    provider: google
    property: G-D2V34CRL34

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 前言: "index.md"
  - 开发环境:
      - "Windows 硬件开发环境搭建": "开发环境/Windows 硬件开发环境搭建.md"
      - "macOS 硬件开发环境搭建": "开发环境/macOS 硬件开发环境搭建.md"
      - "IDE 的选择": "开发环境/IDE 的选择.md"
      - 驱动: "开发环境/驱动.md"
      - 烧录: "开发环境/烧录.md"
      - 调试: "开发环境/调试.md"
  - 工具:
      - 焊接: "工具/焊接.md"
      - 加工: "工具/加工.md"
      - 万用表: "工具/万用表.md"
      - 示波器: "工具/示波器.md"
      - 数控电源: "工具/数控电源.md"
      - "Bambu 3D 打印机": "工具/Bambu 3D 打印机.md"
      - "实物图": "工具/实物图.md"
      - "嘉立创 EDA": "工具/嘉立创 EDA.md"
      - "Arduino IDE": "工具/Arduino IDE.md"
      - "App Inventor": "工具/App Inventor.md"
      - "Bambu Studio": "工具/Bambu Studio.md"
      - "Shapr3D": "工具/Shapr3D.md"
      - "Fusion 360": "工具/Fusion 360.md"
  - 软件模块:
      - "Arduino API": "软件模块/Arduino API.md"
      - "ESP-IDF API": "软件模块/ESP-IDF API.md"
      - "STM32Cube API": "软件模块/STM32Cube API.md"
      - "MicroPython API": "软件模块/MicroPython API.md"
      - "LVGL-library": "软件模块/LVGL-library.md"
      - "Servo-library-Arduino": "软件模块/Servo-library-Arduino.md"
  - 硬件模块:
      - "Arduino UNO R3": "硬件模块/Arduino UNO R3.md"
      - "STM32 Blue Pill（STM32F103C8T6）": "硬件模块/STM32 Blue Pill（STM32F103C8T6）.md"
      - "ESP32-DevKitC": "硬件模块/ESP32-DevKitC.md"
      - "ESP-12E NodeMCU": "硬件模块/ESP-12E NodeMCU.md"
      - "ESP32-CAM": "硬件模块/ESP32-CAM.md"
      - "Raspberry Pi": "硬件模块/Raspberry Pi.md"
  - 理论:
      - "概念扫盲": "理论/概念扫盲.md"
      - "PID": "理论/PID.md"
      - "LQR": "理论/LQR.md"
      - "FOC": "理论/FOC.md"
  - "Basic examples":
      - "点亮 LED": "examples/01-LED Blinking.md"
      - "按钮控制 LED": "examples/02-Button LED.md"
      - "呼吸灯": "examples/03-LED Brightness Control(Breathing light).md"
      - "数模转换": "examples/04-ADC.md"
      - "RGB-LED": "examples/05-RGB-LED.md"
      - "串口控制 LED": "examples/06-Serial Control of LED.md"
      - "7 位数码管": "examples/07-7-Segment Display.md"
      - "LCD 屏幕": "examples/08-LCD.md"
      - "OLED 屏幕": "examples/09-OLED.md"

  - 项目最后: "项目最后.md"
      