site_name: EE notes and examples
site_author: LiangWatcher
site_description: "这是一个专注于技术知识分享的文档网站"
repo_name: ee-notes-and-examples
repo_name: https://github.com/liangshao07/ee-notes-and-examples
copyright: Copyright &copy; 2024-present <a href="https://github.com/liangshao07" target="_blank" rel="noopener noreferrer">LiangWatcher</a>

theme:
  name: material
  language: zh
  include_search_page: false
  search_index_only: true
 
  features:
    - toc.integrate
    - highlightjs
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liangshao07/ee-notes-and-examples

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 前言: "index.md"
  - 开发环境:
      - "Windows 硬件开发环境搭建": "/开发环境/Windows 硬件开发环境搭建.md"
      - "macOS 硬件开发环境搭建": "/开发环境/macOS 硬件开发环境搭建.md"
      - "IDE 的选择": "/开发环境/IDE 的选择.md"
      - 驱动: "/开发环境/驱动.md"
      - 烧录: "/开发环境/烧录.md"
      - 调试: "/开发环境/调试.md"
  - 工具:
      - 焊接: "/工具/焊接.md"
      - 加工: "/工具/加工.md"
      - 万用表: "/工具/万用表.md"
      - 示波器: "/工具/示波器.md"
      - 数控电源: "/工具/数控电源.md"
      - ”Bambu 3D 打印机”: "/工具/Bambu 3D 打印机.md"
      - ”实物图、电路图、仿真模拟”: "/工具/实物图、电路图、仿真模拟.md"
      - ”嘉立创 EDA”: "/工具/嘉立创 EDA.md"
      - ”App Inventor”: "/工具/App Inventor.md"
      - ”Bambu Studio”: "/工具/Bambu Studio.md"
      - ”Shapr3D”: "/工具/Shapr3D.md"
      - ”Fusion 360”: "/工具/Fusion 360.md"
  - 软件模块:
      - ”Arduino API”: "/软件模块/Arduino API.md"
      - ”ESP-IDF API”: "/软件模块/ESP-IDF API.md"
      - ”STM32Cube API”: "/软件模块/STM32Cube API.md"
      - ”MicroPython API”: "/软件模块/MicroPython API.md"
      - ”GPIOzero API”: "/软件模块/GPIOzero API.md"
      - ”RPiGPIO API”: "/软件模块/RPiGPIO API.md"
  - 硬件模块:
      - ”Arduino UNO R3”: "/硬件模块/Arduino UNO R3.md"
      - ”STM32 Blue Pill（STM32F103C8T6）”: "/硬件模块/STM32 Blue Pill（STM32F103C8T6）.md"
      - ”ESP32-DevKitC”: "/硬件模块/ESP32-DevKitC.md"
      - ”ESP-12E NodeMCU”: "/硬件模块/ESP-12E NodeMCU.md"
      - ”ESP32-CAM”: "/硬件模块/ESP32-CAM.md"
  - “example”:
      - "点亮 LED": "/example/LED Blinking.md"
    

