site_name: EE notes and examples
site_url: https://liangwatcher.top
site_author: LiangWatcher
site_description: "这是一个专注于技术知识分享的文档网站"
repo_name: ee-notes-and-examples
repo_name: https://github.com/liangshao07/ee-notes-and-examples
copyright: Copyright &copy; 2024-present <a href="https://github.com/liangshao07" target="_blank" rel="noopener noreferrer">LiangWatcher</a>

theme:
  name: material
  language: zh
  favicon: pic/favicon.ico
  apple-touch-icon-precomposed: pic/mobile_icon.png
  include_search_page: false
  search_index_only: true
 
  features:
    - toc.integrate
    - highlightjs
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes

plugins:
  -search
  -minify:
    minify_html:true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liangshao07/ee-notes-and-examples
  analytics:
    provider: google
    property: G-
 


